[phases.setup]
aptPkgs = ["nodejs", "npm", "python3", "python3-pip", "python3-venv", "chromium-browser", "wget", "curl"]

[phases.install]
cmds = [
  "npm install --prefix backend",
  "pip3 install -r requirements.txt"
]

[phases.build]
cmds = [
  "chmod +x start.sh"
]

[start]
cmd = "sh start.sh"

[phases.build.cache]
directories = ["node_modules", "backend/node_modules", "venv"] 