[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node backend/websocket_server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/socket-status"
healthcheckTimeout = 10

[http]
forwardHeaders = ["Upgrade", "Connection"]
websockets = true
upgradeWebsockets = true

[phases]
setup = { cmds = ["apt-get update", "apt-get install -y curl wget ca-certificates"] } 