[build]
builder = "nixpacks"

[deploy]
startCommand = "sh start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[phases]
setup = { cmds = ["apt-get update", "apt-get install -y curl wget ca-certificates"] } 